"""
Report Builder - Generates markdown reports and ATT&CK Navigator layers.
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Optional
from rich.console import Console

console = Console()


class ReportBuilder:
    """Builds final output artifacts from pipeline results."""

    def build_report(self, results: dict) -> str:
        """Generate a comprehensive markdown report from pipeline results."""
        intel = results.get("intel", {})
        plan = results.get("planner", {})
        purple = results.get("purple", {})
        coverage = purple.get("coverage", {})

        phases = ["recon", "access", "persist", "movement", "exfil"]
        phase_results = {p: results.get(p, {}) for p in phases}

        report = f"""# The Hive - Adversary Emulation Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Threat Actor:** {intel.get("threat_actor", "Unknown")}
**Origin:** {intel.get("origin", "Unknown")}
**Techniques Analyzed:** {len(intel.get("techniques", []))}

---

## Executive Summary

{purple.get("executive_summary", "Emulation pipeline completed. See detailed results below.")}

---

## Detection Coverage Scorecard

| Metric | Value |
|--------|-------|
| Total Techniques | {coverage.get("total", 0)} |
| Likely Detected | {coverage.get("detected", 0)} |
| Likely Missed | {coverage.get("missed", 0)} |
| **Coverage** | **{coverage.get("percentage", 0):.0f}%** |

---

## Threat Actor Profile

- **Name:** {intel.get("threat_actor", "N/A")}
- **Aliases:** {", ".join(intel.get("aliases", []))}
- **Origin:** {intel.get("origin", "N/A")}
- **Targets:** {", ".join(intel.get("targets", []))}
- **Tools:** {", ".join(intel.get("tools", []))}

---

## Extracted Techniques

| # | Technique ID | Name | Tactic |
|---|-------------|------|--------|
"""
        for i, tech in enumerate(intel.get("techniques", []), 1):
            tid = tech.get("id", "?")
            name = tech.get("name", "?")
            tactic = tech.get("tactic", "?")
            report += f"| {i} | {tid} | {name} | {tactic} |\n"

        report += "\n---\n\n## Emulation Plan\n\n"
        for phase_data in plan.get("phases", []):
            phase_name = phase_data.get("name", "unknown").replace("_", " ").title()
            report += f"### Phase: {phase_name}\n\n"
            for tech in phase_data.get("techniques", []):
                report += f"- **{tech.get('id', '?')}** - {tech.get('name', '?')}\n"
            report += "\n"

        report += "---\n\n## Execution Results\n\n"
        for phase_name in phases:
            pr = phase_results.get(phase_name, {})
            if not pr:
                continue
            display = phase_name.replace("_", " ").title()
            report += f"### {display} Phase\n\n"
            for tech in pr.get("techniques_executed", []):
                status = "Executed" if tech.get("success") else "Simulated"
                report += f"- **{tech.get('id', '?')}** ({tech.get('name', '?')}): {status}\n"
            report += "\n"

        report += "---\n\n## Detection Rules Generated\n\n"
        report += f"**Sigma Rules:** {len(purple.get('sigma_rules', []))}\n"
        report += f"**YARA Rules:** {len(purple.get('yara_rules', []))}\n\n"

        for rule in purple.get("sigma_rules", []):
            report += f"### {rule.get('technique_id', '?')} - {rule.get('technique_name', '?')}\n\n"
            report += f"```yaml\n{rule.get('rule_content', '')}\n```\n\n"

        report += "---\n\n## Gap Analysis\n\n"
        gaps = purple.get("gaps", [])
        if gaps:
            report += "| Technique | Gap | Recommendation |\n|-----------|-----|----------------|\n"
            for gap in gaps:
                report += f"| {gap.get('technique', '?')} | {gap.get('gap_type', '?')} | {gap.get('recommendation', '?')} |\n"
        else:
            report += "No significant gaps identified.\n"

        deception = results.get("deception", {})
        decoys = deception.get("decoys", [])
        if decoys:
            report += "\n---\n\n## Active Defense Deception Traps\n\n"
            report += "| Technique | Decoy Type | Target | Description |\n|-----------|------------|--------|-------------|\n"
            for decoy in decoys:
                report += f"| {decoy.get('technique', '?')} | {decoy.get('type', '?')} | {decoy.get('target', '?')} | {decoy.get('description', '?')} |\n"

        report += "\n---\n\n*Report generated by The Hive - Multi-Agent AI Adversary Emulation Pipeline*\n"
        return report

    def build_navigator_layer(self, techniques: list, coverage: dict) -> dict:
        """Generate an ATT&CK Navigator layer JSON."""
        detected_ids = coverage.get("detected_techniques", [])
        missed_ids = coverage.get("missed_techniques", [])

        layer_techniques = []
        for tech in techniques:
            tid = tech.get("id") or tech.get("technique_id", "")
            if tid in detected_ids:
                score = 100
                color = "#27ae60"
                comment = "Detected during emulation"
            elif tid in missed_ids:
                score = 0
                color = "#e74c3c"
                comment = "NOT detected - detection gap"
            else:
                score = 50
                color = "#f39c12"
                comment = "Simulated - detection status unknown"

            layer_techniques.append({
                "techniqueID": tid,
                "score": score,
                "color": color,
                "comment": comment,
                "enabled": True,
            })

        return {
            "name": f"The Hive - {coverage.get('threat_actor', 'Emulation')} Coverage",
            "versions": {"attack": "14", "navigator": "4.9.1", "layer": "4.5"},
            "domain": "enterprise-attack",
            "description": f"Detection coverage for {coverage.get('threat_actor', 'adversary')} emulation. Green=Detected, Red=Missed, Orange=Unknown",
            "sorting": 3,
            "layout": {"layout": "side", "aggregateFunction": "average", "showID": True, "showName": True},
            "gradient": {"colors": ["#e74c3c", "#f39c12", "#27ae60"], "minValue": 0, "maxValue": 100},
            "techniques": layer_techniques,
        }

    def save_all(self, output_dir: str, results: dict) -> None:
        """Save all output artifacts to disk."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        # Save report
        report_md = self.build_report(results)
        (out / "report.md").write_text(report_md, encoding="utf-8")
        # Save explainability report
        explain_md = results.get("explain", {}).get("explainability_report", "")
        if explain_md:
            (out / "explainability_report.md").write_text(explain_md, encoding="utf-8")
            console.print(f"[green]  Saved explainability_report.md[/green]")

        console.print(f"[green]  Saved report.md[/green]")

        # Save Navigator layer
        intel = results.get("intel", {})
        purple = results.get("purple", {})
        coverage_data = purple.get("coverage", {})
        coverage_data["threat_actor"] = intel.get("threat_actor", "Unknown")

        layer = self.build_navigator_layer(intel.get("techniques", []), coverage_data)
        with open(out / "attck_navigator.json", "w") as f:
            json.dump(layer, f, indent=2)
        console.print(f"[green]  Saved attck_navigator.json[/green]")

        # Save Sigma rules
        sigma_dir = out / "sigma_rules"
        sigma_dir.mkdir(exist_ok=True)
        for rule in purple.get("sigma_rules", []):
            tid = rule.get("technique_id", "unknown").replace(".", "_")
            (sigma_dir / f"hive_{tid}.yml").write_text(rule.get("rule_content", ""), encoding="utf-8")
        console.print(f"[green]  Saved {len(purple.get('sigma_rules', []))} Sigma rules[/green]")

        # Save YARA rules
        yara_dir = out / "yara_rules"
        yara_dir.mkdir(exist_ok=True)
        for i, rule in enumerate(purple.get("yara_rules", [])):
            (yara_dir / f"hive_rule_{i}.yar").write_text(rule, encoding="utf-8")
        console.print(f"[green]  Saved {len(purple.get('yara_rules', []))} YARA rules[/green]")

        # Save raw results JSON
        with open(out / "raw_results.json", "w") as f:
            json.dump(results, f, indent=2, default=str)
        console.print(f"[green]  Saved raw_results.json[/green]")
